apiVersion: apps/v1
kind: Deployment
metadata:
  name: parts-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: parts
  template:
    metadata:
      labels:
        app: parts
    spec:
      containers:
        - name: parts
          image: mkrekhovetskyi/parts  #us.gcr.io/partsmarket-415520/parts
          env:
            - name: NATS_URI
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: 'partsmarketing'
            - name: NATS_CLIENT_ID
              valueFrom: 
                fieldRef:
                  fieldPath: metadata.name
            - name: MONGO_URI
              value: 'mongodb://parts-mongo-srv:27017/parts'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: parts-srv
spec:
  selector:
    app: parts
  ports:
    - name: parts
      protocol: TCP
      port: 3000
      targetPort: 3000