apiVersion: apps/v1
kind: Deployment
metadata:
  name: purchase-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: purchase
  template:
    metadata:
      labels:
        app: purchase
    spec:
      containers:
        - name: purchase
          image: mkrekhovetskyi/purchase  #us.gcr.io/purchasemarket-415520/purchase
          env:
            - name: NATS_URI
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: 'partsmarketing'
            - name: NATS_CLIENT_ID
              valueFrom: 
                fieldRef:
                  fieldPath: metadata.name
            - name: MONGO_URI
              value: 'mongodb://purchase-mongo-srv:27017/purchase'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: purchase-srv
spec:
  selector:
    app: purchase
  ports:
    - name: purchase
      protocol: TCP
      port: 3000
      targetPort: 3000