name: deploy-purchase

on:
  push:
    branches:
      - master
    paths:
      - 'purchase/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run:  cd purchase && docker build -t mkrekhovetskyi/purchase .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push mkrekhovetskyi/purchase
#      - uses: digitalocean/action-doctl@v2
#        with:
#          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
#      - run: doctl kebernetes cluster kubeconfig save partsmarket
#      - run: kubectl rollout restart deployment purchase-depl
