name: tests-parts

on:
  pull_request:
    paths:
      - 'parts/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd parts && npm install && npm run test:ci
